Added basic TypeScript typings
eshaz/codec-parser pull request #23
Opened 2022-06-18 08:37 UTC by JohnWeisz

This PR adds `index.d.ts` containing typings, but without descriptions (as of now). This allows `codec-parser` to be used in TypeScript projects nicely.

2022-06-18 16:56 UTC, CharlesSchimmel commented
Could you also update `format` in `package.json` to include formatting TypeScript files, and then run `npm format` and push the changes? Just add `--write **/*.ts` to [this line](https://github.com/JohnWeisz/codec-parser-with-types/blob/master/package.json#L21).

2022-06-18 16:56 UTC, CharlesSchimmel commented
This is so helpful, thanks for doing this!

2022-06-18 16:56 UTC, CharlesSchimmel requested changes

2022-06-18 16:56 UTC, CharlesSchimmel commented on index.d.ts
> +        onCodec?: () => any;
I think this can be narrowed to `(string: codec) => {}`. @eshaz `onCodec` is called with a string that is the name of the codec being used, and is expected to be an arbitrary action?

2022-06-18 16:56 UTC, CharlesSchimmel commented on index.d.ts
> +    declare type OggMimeType = "application/ogg" | "audio/ogg";
Could these also be broken out into individual type aliases for each string?

2022-06-18 16:56 UTC, CharlesSchimmel commented on index.d.ts
> +        onCodecUpdate?: () => any;
`onCodecUpdate` is passed one of the Header types you've defined above; could you make a union of those types (called something like CodecUpdateHeader), and refine this to `( header: { bitrate: number } & CodecUpdateHeader, totalDuration: number) => {}`

2022-06-18 16:56 UTC, CharlesSchimmel commented on package.json
> +  "types": "index.d.ts"
Small thing: I believe it's a soft pattern to put the `types` field near the top, usually after `main`.

2022-06-18 17:07 UTC, eshaz commented on index.d.ts
> +        onCodec?: () => any;
I think it a union could be used here that is dependent on the passed in `mimetype` on instantiation.
 * When the `mimetype` is like `aac` or `mpeg`, then `onCodec` will be called with `aac` and `mpeg` respectively.
 * When the `mimetype` is like `ogg`, then `onCodec` may be called with one of `flac`, `opus`, or `vorbis` depending on the detected codec.

See: https://github.com/eshaz/codec-parser/search?q=onCodec and https://github.com/eshaz/codec-parser#properties

This is something I can add myself later too.

2022-06-18 17:11 UTC, eshaz commented
Thanks @JohnWeisz for your contribution! I've been meaning to add types but you beat me to it :) Feel free to make updates based on the comments here if you want. Otherwise, I'll merge this into a branch and take care of the modifications.

2022-06-19 10:25 UTC, JohnWeisz commented
Thanks, I pushed a few more changes, in particular to get formatting done and flesh out the onCodec callbacks.

Note: I ran prettier locally and it essentially affected every `.js` file in the repo. I didn't push those.

2022-06-19 10:26 UTC, JohnWeisz commented on index.d.ts
> +        onCodec?: () => any;
For now I added an enum to constrain `codec` to the possible codec strings.

2022-06-25 23:31 UTC, eshaz approved these changes

2022-06-25 23:32 UTC, merged